namespace LibraryManager.Views
{
    using LibraryManager.Properties;
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;

    public class DocSection : BasePartialView
    {
        private IContainer components;
        private Label label6;
        private PictureBox BtnSearch;
        private Label label7;
        private TextBox TbxSearch;
        private Button BtnAdd;
        private Button BtnEdit;
        private Button BtnDelete;
        private Button BtnExport;
        private Label label8;
        private ComboBox CbxColumn;
        private Label label1;
        private ComboBox comboBox1;
        private Panel panel1;
        private DataGridView DTProposalContent;
        private Button button1;
        private DataGridViewTextBoxColumn Id;
        private DataGridViewTextBoxColumn Section;
        private DataGridViewTextBoxColumn Location;
        private DataGridViewTextBoxColumn DocType;
        private DataGridViewTextBoxColumn Description;
        private DataGridViewTextBoxColumn Source;
        private DataGridViewTextBoxColumn Updated;
        private DataGridViewTextBoxColumn UpdatedBy;
        private DataGridViewTextBoxColumn ClientUpdated;

        public DocSection(Panel Panel) : base(Panel)
        {
            this.InitializeComponent();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            DataGridViewCellStyle style = new DataGridViewCellStyle();
            DataGridViewCellStyle style2 = new DataGridViewCellStyle();
            DataGridViewCellStyle style3 = new DataGridViewCellStyle();
            this.label6 = new Label();
            this.label7 = new Label();
            this.TbxSearch = new TextBox();
            this.BtnSearch = new PictureBox();
            this.BtnAdd = new Button();
            this.BtnEdit = new Button();
            this.BtnDelete = new Button();
            this.BtnExport = new Button();
            this.label8 = new Label();
            this.CbxColumn = new ComboBox();
            this.label1 = new Label();
            this.comboBox1 = new ComboBox();
            this.panel1 = new Panel();
            this.DTProposalContent = new DataGridView();
            this.button1 = new Button();
            this.Id = new DataGridViewTextBoxColumn();
            this.Section = new DataGridViewTextBoxColumn();
            this.Location = new DataGridViewTextBoxColumn();
            this.DocType = new DataGridViewTextBoxColumn();
            this.Description = new DataGridViewTextBoxColumn();
            this.Source = new DataGridViewTextBoxColumn();
            this.Updated = new DataGridViewTextBoxColumn();
            this.UpdatedBy = new DataGridViewTextBoxColumn();
            this.ClientUpdated = new DataGridViewTextBoxColumn();
            ((ISupportInitialize) this.BtnSearch).BeginInit();
            ((ISupportInitialize) this.DTProposalContent).BeginInit();
            base.SuspendLayout();
            this.label6.AutoSize = true;
            this.label6.FlatStyle = FlatStyle.Flat;
            this.label6.Font = new Font("Segoe UI Semibold", 9f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label6.ForeColor = Color.FromArgb(0x26, 0x26, 0x26);
            this.label6.Location = new Point(8, 6);
            this.label6.Name = "label6";
            this.label6.Size = new Size(0xb1, 15);
            this.label6.TabIndex = 0x11;
            this.label6.Text = "Library Manager > Doc Sections";
            this.label7.AutoSize = true;
            this.label7.FlatStyle = FlatStyle.Flat;
            this.label7.Font = new Font("Segoe UI Semibold", 9f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label7.ForeColor = Color.FromArgb(0x26, 0x26, 0x26);
            this.label7.Location = new Point(15, 0x33);
            this.label7.Name = "label7";
            this.label7.Size = new Size(0x2e, 15);
            this.label7.TabIndex = 0x18;
            this.label7.Text = "Search:";
            this.TbxSearch.BackColor = Color.White;
            this.TbxSearch.Font = new Font("Segoe UI Semibold", 9.5f, FontStyle.Bold);
            this.TbxSearch.ImeMode = ImeMode.Katakana;
            this.TbxSearch.Location = new Point(0x10, 70);
            this.TbxSearch.Name = "TbxSearch";
            this.TbxSearch.Size = new Size(0xc7, 0x18);
            this.TbxSearch.TabIndex = 0x17;
            this.BtnSearch.Anchor = AnchorStyles.None;
            this.BtnSearch.BackColor = Color.FromArgb(0, 0x72, 0xc6);
            this.BtnSearch.BackgroundImageLayout = ImageLayout.Center;
            this.BtnSearch.Cursor = Cursors.Hand;
            //this.BtnSearch.Image = Resources.search;
            this.BtnSearch.Location = new Point(0xd5, 70);
            this.BtnSearch.Name = "BtnSearch";
            this.BtnSearch.Size = new Size(0x18, 0x18);
            this.BtnSearch.SizeMode = PictureBoxSizeMode.StretchImage;
            this.BtnSearch.TabIndex = 0x16;
            this.BtnSearch.TabStop = false;
            this.BtnAdd.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.BtnAdd.BackColor = Color.FromArgb(0, 0x72, 0xc6);
            this.BtnAdd.Cursor = Cursors.Hand;
            this.BtnAdd.FlatAppearance.MouseOverBackColor = Color.FromArgb(0, 100, 190);
            this.BtnAdd.FlatStyle = FlatStyle.Flat;
            this.BtnAdd.Font = new Font("Segoe UI Semibold", 10.5f, FontStyle.Bold);
            this.BtnAdd.ForeColor = Color.White;
            this.BtnAdd.Location = new Point(370, 0x5f);
            this.BtnAdd.Name = "BtnAdd";
            this.BtnAdd.Size = new Size(0x52, 0x1d);
            this.BtnAdd.TabIndex = 0x1b;
            this.BtnAdd.Text = "Add";
            this.BtnAdd.UseVisualStyleBackColor = false;
            this.BtnEdit.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.BtnEdit.BackColor = Color.FromArgb(0, 0x72, 0xc6);
            this.BtnEdit.Cursor = Cursors.Hand;
            this.BtnEdit.Enabled = false;
            this.BtnEdit.FlatAppearance.MouseOverBackColor = Color.FromArgb(0, 100, 190);
            this.BtnEdit.FlatStyle = FlatStyle.Flat;
            this.BtnEdit.Font = new Font("Segoe UI Semibold", 10.5f, FontStyle.Bold);
            this.BtnEdit.ForeColor = Color.White;
            this.BtnEdit.Location = new Point(0x1c8, 0x5f);
            this.BtnEdit.Name = "BtnEdit";
            this.BtnEdit.Size = new Size(0x51, 0x1d);
            this.BtnEdit.TabIndex = 0x1a;
            this.BtnEdit.Text = "Edit";
            this.BtnEdit.UseVisualStyleBackColor = false;
            this.BtnDelete.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.BtnDelete.BackColor = Color.FromArgb(0, 0x72, 0xc6);
            this.BtnDelete.Cursor = Cursors.Hand;
            this.BtnDelete.Enabled = false;
            this.BtnDelete.FlatAppearance.MouseOverBackColor = Color.FromArgb(0, 100, 190);
            this.BtnDelete.FlatStyle = FlatStyle.Flat;
            this.BtnDelete.Font = new Font("Segoe UI Semibold", 10.5f, FontStyle.Bold);
            this.BtnDelete.ForeColor = Color.White;
            this.BtnDelete.Location = new Point(0x21d, 0x5f);
            this.BtnDelete.Name = "BtnDelete";
            this.BtnDelete.Size = new Size(0x52, 0x1d);
            this.BtnDelete.TabIndex = 0x19;
            this.BtnDelete.Text = "Delete";
            this.BtnDelete.UseVisualStyleBackColor = false;
            this.BtnExport.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.BtnExport.BackColor = Color.FromArgb(0x27, 0x27, 0x27);
            this.BtnExport.Cursor = Cursors.Hand;
            this.BtnExport.Enabled = false;
            this.BtnExport.FlatAppearance.MouseOverBackColor = Color.FromArgb(0, 100, 190);
            this.BtnExport.FlatStyle = FlatStyle.Flat;
            this.BtnExport.Font = new Font("Segoe UI Semibold", 10.5f, FontStyle.Bold);
            this.BtnExport.ForeColor = Color.White;
            this.BtnExport.Location = new Point(0x21d, 0x80);
            this.BtnExport.Name = "BtnExport";
            this.BtnExport.Size = new Size(0x52, 0x1d);
            this.BtnExport.TabIndex = 0x1c;
            this.BtnExport.Text = "Export";
            this.BtnExport.UseVisualStyleBackColor = false;
            this.label8.AutoSize = true;
            this.label8.FlatStyle = FlatStyle.Flat;
            this.label8.Font = new Font("Segoe UI Semibold", 9f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label8.ForeColor = Color.FromArgb(0x26, 0x26, 0x26);
            this.label8.Location = new Point(13, 0x75);
            this.label8.Name = "label8";
            this.label8.Size = new Size(0x51, 15);
            this.label8.TabIndex = 30;
            this.label8.Text = "Filter Column:";
            this.CbxColumn.DropDownStyle = ComboBoxStyle.DropDownList;
            this.CbxColumn.FlatStyle = FlatStyle.Popup;
            this.CbxColumn.Font = new Font("Segoe UI Semibold", 9.5f, FontStyle.Bold);
            this.CbxColumn.FormattingEnabled = true;
            this.CbxColumn.Location = new Point(0x10, 0x88);
            this.CbxColumn.Name = "CbxColumn";
            this.CbxColumn.Size = new Size(150, 0x19);
            this.CbxColumn.TabIndex = 0x1d;
            this.label1.AutoSize = true;
            this.label1.FlatStyle = FlatStyle.Flat;
            this.label1.Font = new Font("Segoe UI Semibold", 9f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label1.ForeColor = Color.FromArgb(0x26, 0x26, 0x26);
            this.label1.Location = new Point(0xac, 0x75);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x44, 15);
            this.label1.TabIndex = 0x20;
            this.label1.Text = "Filter Value:";
            this.comboBox1.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBox1.FlatStyle = FlatStyle.Popup;
            this.comboBox1.Font = new Font("Segoe UI Semibold", 9.5f, FontStyle.Bold);
            this.comboBox1.FormattingEnabled = true;
            this.comboBox1.Location = new Point(0xaf, 0x88);
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.Size = new Size(150, 0x19);
            this.comboBox1.TabIndex = 0x1f;
            this.panel1.Location = new Point(0x14b, 0x86);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(0xce, 0x1b);
            this.panel1.TabIndex = 0x21;
            this.DTProposalContent.AllowUserToAddRows = false;
            this.DTProposalContent.AllowUserToDeleteRows = false;
            this.DTProposalContent.AllowUserToResizeRows = false;
            this.DTProposalContent.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.DTProposalContent.BackgroundColor = Color.White;
            this.DTProposalContent.BorderStyle = BorderStyle.None;
            this.DTProposalContent.CellBorderStyle = DataGridViewCellBorderStyle.None;
            this.DTProposalContent.ClipboardCopyMode = DataGridViewClipboardCopyMode.Disable;
            this.DTProposalContent.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
            style.Alignment = DataGridViewContentAlignment.MiddleLeft;
            style.BackColor = Color.White;
            style.Font = new Font("Segoe UI", 8.5f, FontStyle.Bold);
            style.ForeColor = SystemColors.WindowText;
            style.SelectionBackColor = Color.FromArgb(0, 0x72, 0xc6);
            style.SelectionForeColor = SystemColors.HighlightText;
            style.WrapMode = DataGridViewTriState.False;
            this.DTProposalContent.ColumnHeadersDefaultCellStyle = style;
            this.DTProposalContent.ColumnHeadersHeight = 0x19;
            this.DTProposalContent.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            DataGridViewColumn[] dataGridViewColumns = new DataGridViewColumn[] { this.Id, this.Section, this.Location, this.DocType, this.Description, this.Source, this.Updated, this.UpdatedBy, this.ClientUpdated };
            this.DTProposalContent.Columns.AddRange(dataGridViewColumns);
            this.DTProposalContent.Cursor = Cursors.Hand;
            style2.Alignment = DataGridViewContentAlignment.MiddleLeft;
            style2.BackColor = Color.White;
            style2.Font = new Font("Segoe UI", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            style2.ForeColor = Color.FromArgb(0x23, 0x23, 0x23);
            style2.SelectionBackColor = Color.FromArgb(0, 0x72, 0xc6);
            style2.SelectionForeColor = SystemColors.HighlightText;
            style2.WrapMode = DataGridViewTriState.False;
            this.DTProposalContent.DefaultCellStyle = style2;
            this.DTProposalContent.EnableHeadersVisualStyles = false;
            this.DTProposalContent.GridColor = Color.White;
            this.DTProposalContent.Location = new Point(12, 0xa7);
            this.DTProposalContent.Name = "DTProposalContent";
            this.DTProposalContent.RowHeadersBorderStyle = DataGridViewHeaderBorderStyle.Single;
            style3.Alignment = DataGridViewContentAlignment.MiddleLeft;
            style3.BackColor = SystemColors.Control;
            style3.Font = new Font("Segoe UI", 9.75f, FontStyle.Bold, GraphicsUnit.Point, 0);
            style3.ForeColor = SystemColors.WindowText;
            style3.SelectionBackColor = SystemColors.Highlight;
            style3.SelectionForeColor = SystemColors.HighlightText;
            style3.WrapMode = DataGridViewTriState.True;
            this.DTProposalContent.RowHeadersDefaultCellStyle = style3;
            this.DTProposalContent.RowHeadersVisible = false;
            this.DTProposalContent.RowHeadersWidthSizeMode = DataGridViewRowHeadersWidthSizeMode.DisableResizing;
            this.DTProposalContent.ScrollBars = ScrollBars.Vertical;
            this.DTProposalContent.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.DTProposalContent.Size = new Size(0x263, 0x134);
            this.DTProposalContent.TabIndex = 0x22;
            this.button1.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.button1.BackColor = Color.FromArgb(0x27, 0x27, 0x27);
            this.button1.Cursor = Cursors.Hand;
            this.button1.Enabled = false;
            this.button1.FlatAppearance.MouseOverBackColor = Color.FromArgb(0, 100, 190);
            this.button1.FlatStyle = FlatStyle.Flat;
            this.button1.Font = new Font("Segoe UI Semibold", 10.5f, FontStyle.Bold);
            this.button1.ForeColor = Color.White;
            this.button1.Location = new Point(0x11a, 0x5f);
            this.button1.Name = "button1";
            this.button1.Size = new Size(0x52, 0x1d);
            this.button1.TabIndex = 0x23;
            this.button1.Text = "Move";
            this.button1.UseVisualStyleBackColor = false;
            this.Id.HeaderText = "Order";
            this.Id.Name = "Id";
            this.Id.Width = 0x2d;
            this.Section.HeaderText = "Section";
            this.Section.Name = "Section";
            this.Section.Width = 0x41;
            this.Location.HeaderText = "Location";
            this.Location.Name = "Location";
            this.Location.Width = 0x41;
            this.DocType.HeaderText = "DocType";
            this.DocType.Name = "DocType";
            this.DocType.Width = 0x41;
            this.Description.HeaderText = "Description";
            this.Description.Name = "Description";
            this.Description.Width = 90;
            this.Source.HeaderText = "Source";
            this.Source.Name = "Source";
            this.Source.Width = 0x41;
            this.Updated.HeaderText = "Updated";
            this.Updated.Name = "Updated";
            this.Updated.Width = 0x41;
            this.UpdatedBy.HeaderText = "UpdatedBy";
            this.UpdatedBy.Name = "UpdatedBy";
            this.UpdatedBy.Width = 0x4b;
            this.ClientUpdated.HeaderText = "ClientUpdated";
            this.ClientUpdated.Name = "ClientUpdated";
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = AutoScaleMode.Font;
            this.BackColor = Color.WhiteSmoke;
            base.ClientSize = new Size(0x27b, 0x1f9);
            base.Controls.Add(this.button1);
            base.Controls.Add(this.DTProposalContent);
            base.Controls.Add(this.panel1);
            base.Controls.Add(this.label1);
            base.Controls.Add(this.comboBox1);
            base.Controls.Add(this.label8);
            base.Controls.Add(this.CbxColumn);
            base.Controls.Add(this.BtnExport);
            base.Controls.Add(this.BtnAdd);
            base.Controls.Add(this.BtnEdit);
            base.Controls.Add(this.BtnDelete);
            base.Controls.Add(this.BtnSearch);
            base.Controls.Add(this.label7);
            base.Controls.Add(this.TbxSearch);
            base.Controls.Add(this.label6);
            base.FormBorderStyle = FormBorderStyle.None;
            base.Name = "DocSection";
            this.Text = "DocSection";
            ((ISupportInitialize) this.BtnSearch).EndInit();
            ((ISupportInitialize) this.DTProposalContent).EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }
    }
}

